"""
Generate a DRAFT semantic_layer.yaml for a return from its schema.json and
description_samples.json.

What can be derived mechanically is derived here: which tables are vertical and
what their total row is, which _DOM/_OVE column pairs compose a total, and which
tables are _PART_A/_PART_B siblings of the same section.

What CANNOT be derived is the join graph. This script only proposes the joins it
is confident about — sibling parts of the same section, on CODE + RDATE — and
that list is deliberately conservative, because the graph is an ALLOW-LIST: once
any edge exists, src/sql_generator.validate_sql rejects every pair that is not
declared. Under-declaring makes the system refuse a legitimate join (visible,
fixable); over-declaring re-opens the invented-join failures this is meant to
stop (silent, wrong numbers). Review and extend the file by hand.

Usage:
    python -m embedding_building.build_semantic_layer                       # active EMBEDDING_DIR
    python -m embedding_building.build_semantic_layer embedding_building/cims_raq_quarterly
"""

import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src import config
from src.sql_generator import _find_total_row


def _load(path):
    try:
        with open(path, encoding="utf-8") as fh:
            return json.load(fh)
    except FileNotFoundError:
        return None


def _yaml_quote(value: str) -> str:
    """Double-quoted YAML scalar — these values contain colons, brackets and quotes."""
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"') + '"'


def build(target_dir: str) -> str:
    schema = _load(os.path.join(target_dir, "schema.json"))
    if schema is None:
        raise SystemExit(f"No schema.json in {target_dir}")
    samples = _load(os.path.join(target_dir, "description_samples.json")) or {}
    needs_trim = _load(os.path.join(target_dir, "needs_trim.json")) or {}

    columns_by_table = {
        t["table"]: [c["name"] for c in t.get("columns") or []] for t in schema
    }

    # ── vertical tables ──────────────────────────────────────────────────────
    vertical = {}
    for table, col_samples in samples.items():
        for col, values in col_samples.items():
            total_row = _find_total_row(values)
            padded = any(v != v.strip() for v in values)
            vertical[table] = {
                "label_column": col,
                "total_row": total_row,
                "needs_trim": padded or col in (needs_trim.get(table) or []),
                "value_count": len(values),
            }
            break   # one label column per table in this schema

    # ── DOM / OVE column pairs ───────────────────────────────────────────────
    dom_ove = {}
    for table, cols in columns_by_table.items():
        lowered = {c.lower() for c in cols}
        pairs = []
        for col in sorted(lowered):
            if col.endswith("_dom"):
                counterpart = col[:-4] + "_ove"
                if counterpart in lowered:
                    pairs.append([col, counterpart])
        if pairs:
            dom_ove[table] = pairs

    # ── multi-part sibling groups ────────────────────────────────────────────
    groups = {}
    for table in columns_by_table:
        m = re.match(r"^(?P<prefix>.*)_part_[ab](?P<suffix>.*)$", table.lower())
        if m:
            groups.setdefault((m.group("prefix"), m.group("suffix")), []).append(table)
    multipart = [sorted(v) for v in groups.values() if len(v) > 1]

    # ── proposed joins: sibling parts only ───────────────────────────────────
    join_edges = []
    for group in multipart:
        for i, left in enumerate(group):
            for right in group[i + 1:]:
                join_edges.append({
                    "tables": [left, right],
                    "condition": f"{left.upper()}.CODE = {right.upper()}.CODE "
                                 f"AND {left.upper()}.RDATE = {right.upper()}.RDATE",
                    "note": "sibling parts of the same section; same entity and period",
                })

    # ── render ───────────────────────────────────────────────────────────────
    out = [
        "# Semantic layer — DRAFT, generated by embedding_building/build_semantic_layer.py",
        "#",
        "# join_graph is an ALLOW-LIST. Once any edge exists here, validate_sql rejects",
        "# every table pair that is NOT listed. Only sibling _PART_A/_PART_B pairs are",
        "# proposed automatically; add other legitimate joins by hand, and delete any",
        "# proposed edge that is not actually meaningful.",
        "#",
        "# Regenerating overwrites this file — copy your hand-authored edits first.",
        "",
        "join_graph:",
    ]
    if join_edges:
        for edge in join_edges:
            out.append(f"  - tables: [{edge['tables'][0]}, {edge['tables'][1]}]")
            out.append(f"    condition: {_yaml_quote(edge['condition'])}")
            out.append(f"    note: {_yaml_quote(edge['note'])}")
    else:
        out.append("  []   # nothing derivable; joins fall back to CODE+RDATE checks only")

    out += ["", "vertical:"]
    for table in sorted(vertical):
        spec = vertical[table]
        out.append(f"  {table}:")
        out.append(f"    label_column: {spec['label_column']}")
        if spec["total_row"]:
            out.append(f"    total_row: {_yaml_quote(spec['total_row'])}")
        else:
            out.append("    total_row: null   # no total row detected — check by hand")
        out.append(f"    needs_trim: {str(bool(spec['needs_trim'])).lower()}")
        out.append(f"    # {spec['value_count']} distinct sampled values")

    out += ["", "dom_ove:"]
    if dom_ove:
        for table in sorted(dom_ove):
            out.append(f"  {table}:")
            for dom, ove in dom_ove[table]:
                out.append(f"    - [{dom}, {ove}]")
    else:
        out.append("  {}")

    out += ["", "multipart:"]
    if multipart:
        for group in multipart:
            out.append(f"  - [{', '.join(group)}]")
    else:
        out.append("  []")

    out += [
        "",
        "# Named business definitions. Hand-authored: nothing in the DDL states these.",
        "# Any metric named here that appears in a question is injected into the prompt.",
        "metrics: {}",
        "",
        "# Query-side vocabulary. Promote the regexes in src/retriever.py:_QUERY_EXPANSIONS",
        "# here as they are reviewed, so the vocabulary is data rather than code.",
        "synonyms: {}",
        "",
    ]
    return "\n".join(out)


def main():
    target_dir = sys.argv[1] if len(sys.argv) > 1 else config.EMBEDDING_DIR
    content = build(target_dir)
    out_path = os.path.join(target_dir, "semantic_layer.yaml")

    if os.path.exists(out_path):
        backup = out_path + ".bak"
        os.replace(out_path, backup)
        print(f"  existing file moved to {backup}")

    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write(content)

    # ASCII only: the Windows console here is cp1252 and dies on emoji/arrows.
    print(f"[OK] Draft semantic layer -> {out_path}")
    print("   Review join_graph before relying on it: it is an allow-list.")


if __name__ == "__main__":
    main()
