"""
Pull authoritative key metadata from Oracle: primary keys, foreign keys, unique
constraints, and NOT NULL flags.

The checked-in data/schema.sql is generated by extract_schema.py from
ALL_TAB_COLUMNS alone, so it declares no keys at all — which is why schema.json
carried no relationship information and the model had to guess join predicates.
Oracle's dictionary views are the real source of truth, so read them directly.

Usage:
    python embedding_building/extract_constraints.py                 # all tables
    python embedding_building/extract_constraints.py CIMS_RAQ_Q_%    # LIKE filter

Writes data/constraints.json:
    { "<table_lower>": { "primary_key": [...],
                         "foreign_keys": [{"columns", "ref_table", "ref_columns"}],
                         "unique": [[...]],
                         "not_null": [...] } }

Import as a library instead of shelling out:
    from embedding_building.extract_constraints import fetch_constraints
    constraints = fetch_constraints()             # dict, ready for build_schema_json
"""

import sys
import os
import json
from collections import defaultdict

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import oracledb
from src.config import DB_HOST, DB_PORT, DB_SERVICE, DB_USER, DB_PASSWORD

SCHEMA = DB_USER.upper()
OUTPUT_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "data", "constraints.json",
)


def _new_entry():
    return {"primary_key": [], "foreign_keys": [], "unique": [], "not_null": []}


def fetch_constraints(table_like: str | None = None) -> dict:
    """
    Read PK / FK / UNIQUE / NOT NULL metadata for the configured schema.

    Returns a dict keyed by lowercase table name in the shape that
    formatter.build_schema_json(constraints=...) expects. Tables with no
    constraints at all are omitted.
    """
    dsn = f"{DB_HOST}:{DB_PORT}/{DB_SERVICE}"
    binds = {"owner": SCHEMA}
    table_filter = ""
    if table_like:
        table_filter = " AND c.table_name LIKE :tbl"
        binds["tbl"] = table_like.upper()

    constraints = defaultdict(_new_entry)

    with oracledb.connect(user=DB_USER, password=DB_PASSWORD, dsn=dsn) as conn:
        cur = conn.cursor()

        # ── Primary keys and unique constraints ──────────────────────────────
        # POSITION orders multi-column keys correctly (CODE, RDATE, <label>).
        cur.execute(f"""
            SELECT c.table_name, c.constraint_name, c.constraint_type,
                   cc.column_name, cc.position
            FROM   all_constraints c
            JOIN   all_cons_columns cc
                   ON  cc.owner = c.owner
                   AND cc.constraint_name = c.constraint_name
            WHERE  c.owner = :owner
              AND  c.constraint_type IN ('P', 'U'){table_filter}
            ORDER  BY c.table_name, c.constraint_name, cc.position
        """, binds)

        unique_groups = defaultdict(list)
        for tname, cname, ctype, col, _pos in cur.fetchall():
            table = tname.lower()
            if ctype == "P":
                constraints[table]["primary_key"].append(col.lower())
            else:
                unique_groups[(table, cname)].append(col.lower())

        for (table, _cname), cols in unique_groups.items():
            constraints[table]["unique"].append(cols)

        # ── Foreign keys ─────────────────────────────────────────────────────
        # r_constraint_name points at the referenced PK/UNIQUE constraint, so the
        # referenced table and columns come from a second lookup on that name.
        cur.execute(f"""
            SELECT c.table_name, c.constraint_name,
                   cc.column_name, cc.position,
                   rc.table_name AS ref_table, rcc.column_name AS ref_column
            FROM   all_constraints c
            JOIN   all_cons_columns cc
                   ON  cc.owner = c.owner
                   AND cc.constraint_name = c.constraint_name
            JOIN   all_constraints rc
                   ON  rc.owner = c.r_owner
                   AND rc.constraint_name = c.r_constraint_name
            JOIN   all_cons_columns rcc
                   ON  rcc.owner = rc.owner
                   AND rcc.constraint_name = rc.constraint_name
                   AND rcc.position = cc.position
            WHERE  c.owner = :owner
              AND  c.constraint_type = 'R'{table_filter}
            ORDER  BY c.table_name, c.constraint_name, cc.position
        """, binds)

        fk_groups = defaultdict(lambda: {"columns": [], "ref_table": "", "ref_columns": []})
        for tname, cname, col, _pos, ref_table, ref_col in cur.fetchall():
            key = (tname.lower(), cname)
            fk_groups[key]["columns"].append(col.lower())
            fk_groups[key]["ref_table"] = ref_table.lower()
            fk_groups[key]["ref_columns"].append(ref_col.lower())

        for (table, _cname), fk in fk_groups.items():
            constraints[table]["foreign_keys"].append(fk)

        # ── NOT NULL ─────────────────────────────────────────────────────────
        nn_filter = " AND table_name LIKE :tbl" if table_like else ""
        cur.execute(f"""
            SELECT table_name, column_name
            FROM   all_tab_columns
            WHERE  owner = :owner
              AND  nullable = 'N'{nn_filter}
            ORDER  BY table_name, column_id
        """, binds)

        for tname, col in cur.fetchall():
            constraints[tname.lower()]["not_null"].append(col.lower())

    # Drop tables that ended up with nothing (can happen for the NOT NULL pass
    # creating an empty entry via defaultdict access).
    return {
        table: entry for table, entry in constraints.items()
        if entry["primary_key"] or entry["foreign_keys"] or entry["unique"] or entry["not_null"]
    }


def main():
    table_like = sys.argv[1] if len(sys.argv) > 1 else None
    print(f"Reading constraints from {DB_HOST}:{DB_PORT}/{DB_SERVICE} as {SCHEMA}"
          + (f" (LIKE {table_like})" if table_like else ""))

    constraints = fetch_constraints(table_like)

    pk_count = sum(1 for e in constraints.values() if e["primary_key"])
    fk_count = sum(len(e["foreign_keys"]) for e in constraints.values())
    print(f"  tables with metadata : {len(constraints)}")
    print(f"  primary keys         : {pk_count}")
    print(f"  foreign keys         : {fk_count}")

    if not pk_count and not fk_count:
        # Worth saying loudly: these regulatory tables may genuinely have no
        # declared keys, in which case the join graph has to be hand-authored in
        # semantic_layer.yaml instead of extracted.
        print("\n  ⚠  No PK/FK declared anywhere in this schema.")
        print("     The join graph must be hand-authored in semantic_layer.yaml.")

    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as fh:
        json.dump(constraints, fh, indent=2)

    print(f"\n✅ Constraints written → {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
